name: Tracker Seiko SBTR027

on:
    schedule:
        # Le chiffre 3 correspond au mercredi.
        # 09:00 UTC correspond à 11:00 heure d'été en Belgique.
        - cron: '0 9 * * 3'
    workflow_dispatch: # Bouton magique pour forcer un test quand je veux

jobs:
    lancer-agent:
        runs-on: ubuntu-latest
        steps:
            - name: 📥 Récupérer le code
              uses: actions/checkout@v4

            - name: 🐍 Installer Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
                  cache: 'pip'

            - name: 📦 Installer les outils
              run: pip install -r requirements.txt

            - name: 🚀 Réveiller l'Agent IA (1 semaine sur 2)
              env:
                  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                  SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
              run: |
                  # 1. On récupère le numéro de la semaine en cours (ex: 34)
                  SEMAINE=$(date +%V)

                  # 2. Si j'ai avez cliqué moi-même sur le bouton "Run workflow" sur GitHub
                  if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
                    echo "Lancement manuel détecté ! On ignore le calendrier et on lance l'agent..."
                    python main.py
                    
                  # 3. Si c'est le déclenchement automatique et que la semaine est IMPAIRE (ex: 35)
                  elif [ $((SEMAINE % 2)) -eq 1 ]; then
                    echo "Semaine impaire ($SEMAINE). C'est la semaine de repos de l'agent. À mercredi prochain !"
                    
                  # 4. Si c'est le déclenchement automatique et que la semaine est PAIRE (ex: 36)
                  else
                    echo "Semaine paire ($SEMAINE). Démarrage de la mission de recherche !"
                    python main.py
                  fi
